[versions]
agp = "8.2.0-alpha14"
kotlin = "1.9.0"
room = "2.5.2"
aboutLibraries = '10.6.1'
compose = '1.5.0-rc01'
hilt = "2.46"
hilt-navigation = "1.0.0"
datastore-preferences = "1.0.0"
appcompat = "1.7.0-alpha03"
lifecycle-runtime = "2.6.1"
core-ktx = "1.10.1"
activity-compose = "1.7.2"
material3 = "1.2.0-alpha04"
accompanist-pager = "0.28.0"
accompanist-systemuicontroller = "0.28.0"
navigation-compose = "2.7.0-rc01"
acra = "5.9.7"
ksp = "1.9.0-1.0.12"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx"}
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose"}
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime"}
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime"}
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist-pager" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
aboutLibraries = { group = "com.mikepenz", name = "aboutlibraries-compose", version.ref = "aboutLibraries" }
acra-dialog = { group = "ch.acra", name = "acra-dialog", version.ref = "acra" }
acra-mail = { group = "ch.acra", name = "acra-mail", version.ref = "acra" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }